-- TBL_SYS_AUDIT_LOG 생성
-- Phase 2-4: Centralized Audit Logging

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TBL_SYS_AUDIT_LOG')
BEGIN
    CREATE TABLE TBL_SYS_AUDIT_LOG (
        LOG_ID INT IDENTITY(1,1) PRIMARY KEY,
        TABLE_NAME VARCHAR(100) NOT NULL,
        ACTION_TYPE VARCHAR(10) NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
        TARGET_PK VARCHAR(255) NOT NULL,  -- 대상 데이터의 PK 값
        USER_ID VARCHAR(50) NOT NULL,     -- 작업자 ID
        LOG_DTM DATETIME DEFAULT GETDATE()
    );
END
