server {
    listen 8081;
    server_name _;

    location / {
        root /home/itscore/ItscoreMES/frontend/dist-dev;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://localhost:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
