-- PFMES Master Data Referential Integrity Setup
-- Phase 2-1: Data Cleanup and Adding Foreign Key Constraints

-- 0. Data Cleanup: Convert empty strings to NULL or valid defaults
-- For TBL_COM_GOODS.PLANTCD (NOT NULL), use a valid default if empty
UPDATE TBL_COM_GOODS SET PLANTCD = 'PROC_P01' WHERE PLANTCD = '' OR PLANTCD IS NULL;

-- For nullable columns, convert empty strings to NULL to satisfy FKs if they reference PKs
UPDATE TBL_COM_GOODS SET COMPANYCD = NULL WHERE COMPANYCD = '';
UPDATE TBL_COM_FACTORY SET PLANTCD = NULL WHERE PLANTCD = '';
UPDATE TBL_COM_DEPT SET FACTORYCD = NULL WHERE FACTORYCD = '';

-- Delete orphaned BOM records that reference non-existent goods
DELETE FROM TBL_COM_BOM WHERE PAR_PARTNO NOT IN (SELECT PARTNO FROM TBL_COM_GOODS);
DELETE FROM TBL_COM_BOM WHERE CHILD_PARTNO NOT IN (SELECT PARTNO FROM TBL_COM_GOODS);

-- 1. Factory -> Plant
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_FACTORY_PLANT')
BEGIN
    ALTER TABLE TBL_COM_FACTORY
    ADD CONSTRAINT FK_FACTORY_PLANT FOREIGN KEY (PLANTCD)
    REFERENCES TBL_COM_PLANT(PLANTCD);
END

-- 2. Dept -> Factory
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_DEPT_FACTORY')
BEGIN
    ALTER TABLE TBL_COM_DEPT
    ADD CONSTRAINT FK_DEPT_FACTORY FOREIGN KEY (FACTORYCD)
    REFERENCES TBL_COM_FACTORY(FACTORYCD);
END

-- 3. Goods -> Plant
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_GOODS_PLANT')
BEGIN
    ALTER TABLE TBL_COM_GOODS
    ADD CONSTRAINT FK_GOODS_PLANT FOREIGN KEY (PLANTCD)
    REFERENCES TBL_COM_PLANT(PLANTCD);
END

-- 4. Goods -> Company
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_GOODS_COMPANY')
BEGIN
    ALTER TABLE TBL_COM_GOODS
    ADD CONSTRAINT FK_GOODS_COMPANY FOREIGN KEY (COMPANYCD)
    REFERENCES TBL_COM_COMPANY(COMPANYCD);
END

-- 5. BOM -> Goods (Parent)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_BOM_PARENT_GOODS')
BEGIN
    ALTER TABLE TBL_COM_BOM
    ADD CONSTRAINT FK_BOM_PARENT_GOODS FOREIGN KEY (PAR_PARTNO)
    REFERENCES TBL_COM_GOODS(PARTNO);
END

-- 6. BOM -> Goods (Child)
IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = 'FK_BOM_CHILD_GOODS')
BEGIN
    ALTER TABLE TBL_COM_BOM
    ADD CONSTRAINT FK_BOM_CHILD_GOODS FOREIGN KEY (CHILD_PARTNO)
    REFERENCES TBL_COM_GOODS(PARTNO);
END
